# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
	# checkout release branch
	#ensure_git_status_clean

	# clear data
	clear_derived_data 
	xcclean(
	scheme: "GBShop",
	workspace: "GBShop.xcworkspace" 
	)

	# update a dependencies
	cocoapods( 
	use_bundle_exec: false
	)

	# run tests
	run_tests

	# make screenshots
	capture_ios_screenshots
end

	lane :project do 
	increment_build_number
	set_info_plist_value(path: "./GBShop/Environments/Info.plist", key:
	"CFBundleShortVersionString", value: "2.0")

	gym(
	scheme: "GBShop", 
	configuration: "Debug", 
	export_method: "development", 
	include_symbols: true, 
	include_bitcode: true, 
	silent: false
	)

	# commit changes to git
	versionNumber = get_version_number 
	buildNumber = get_build_number
	tag = "#{versionNumber}.#{buildNumber}"
	# git_add
	git_add(path: ["./Podfile.lock", "./GBShop.xcodeproj/project.pbxproj", "./GBShopTests/Info.plist", "./GBShop/Environment/Info.plist", "./GBShopUITests/Info.plist"])
	git_commit(path: ["./Podfile.lock", "./GBShop.xcodeproj/project.pbxproj", "./GBShopTests/Info.plist", "./GBShop/Environment/Info.plist", "./GBShopUITests/Info.plist"], message: "verson up")
	add_git_tag( 
	tag: tag
	)

	upload_to_testflight(
	username: "asdasd@asdasd.com", 
	app_identifier: "com.32eref.app", 
	itc_provider: "shjdghsagfhsdfhg"
	)

    # add actions here: https://docs.fastlane.tools/actions
  end
end
